version: '3.5'
services:
  api:
    build: ./server

    env_file:
      - ./.env
    
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        python manage.py runserver 0.0.0.0:8000
        "


    networks:
      - app-net
    volumes:
      - ./server:/home/server
      - static-vol:/home/server/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      

  frontend:
    build: ./client
    networks:
      - app-net
    volumes:
      - ./client:/home/client
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"


  nginx:
    build: ./nginx 
    networks:
      - app-net
    volumes:
      - static-vol:/var/www/project/static
    ports:
    - "80:80"
    depends_on:
      - api

networks:
  app-net:
volumes:
  static-vol:
  postgres_data:

